// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>


SEXP R3CPET_RunHLDA(SEXP DocumentsSEXP, SEXP max_iterSEXP, SEXP max_timeSEXP);

R_CallMethodDef callMethods[]  = {
  {"R3CPET_RunHLDA", (DL_FUNC) &R3CPET_RunHLDA, 6},
  {NULL, NULL, 0}
};

void R_init_R3CPET(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

