// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RunHLDA
Rcpp::List RunHLDA(List Documents, int max_iter, int max_time, double eta, double gamma, double alpha);
RcppExport SEXP R3CPET_RunHLDA(SEXP DocumentsSEXP, SEXP max_iterSEXP, SEXP max_timeSEXP, SEXP etaSEXP, SEXP gammaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type Documents(DocumentsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(RunHLDA(Documents, max_iter, max_time, eta, gamma, alpha));
    return __result;
END_RCPP
}
