// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// RunHLDA
Rcpp::List RunHLDA(List Documents, int max_iter = 500, int max_time = 3600);
RcppExport SEXP R3CPET_RunHLDA(SEXP DocumentsSEXP, SEXP max_iterSEXP, SEXP max_timeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type Documents(DocumentsSEXP );
        Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP );
        Rcpp::traits::input_parameter< int >::type max_time(max_timeSEXP );
        Rcpp::List __result = RunHLDA(Documents, max_iter, max_time);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
