# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunHLDA <- function(Documents, max_iter = 500L, max_time = 3600L) {
    .Call('R3CPET_RunHLDA', PACKAGE = 'R3CPET', Documents, max_iter, max_time)
}

