# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunHLDA <- function(Documents, max_iter = 500L, max_time = 3600L, eta = 0.01, gamma = 1.0, alpha = 1.0) {
    .Call(`_R3CPET_RunHLDA`, Documents, max_iter, max_time, eta, gamma, alpha)
}

